// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import CollectController from './actions/collect_controller'
import DialogController from './dialog_controller'
import FavouriteController from './actions/favourite_controller'
import HistoryChartController from './history_chart_controller'
import HistoryItemController from './history_item_controller'
import LocalTimeController from './local_time_controller'
import ReadController from './actions/read_controller'
import SwiperController from './swiper_controller'
import WishlistController from './actions/wishlist_controller'
import ReadRangeController from './read_range_controller'

application.register('collect', CollectController)
application.register('dialog', DialogController)
application.register('favourite', FavouriteController)
application.register('history-chart', HistoryChartController)
application.register('history-item', HistoryItemController)
application.register('local-time', LocalTimeController)
application.register('read', ReadController)
application.register('swiper', SwiperController)
application.register('wishlist', WishlistController)
application.register('read-range', ReadRangeController)
